# Generated by Django 4.1.5 on 2023-04-22 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "productname",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "productoldprice",
                    models.CharField(max_length=200, verbose_name="Precio normal"),
                ),
                (
                    "productprice",
                    models.CharField(max_length=200, verbose_name="Precio de venta"),
                ),
                (
                    "productdiscount",
                    models.CharField(max_length=200, verbose_name="Valor de descuento"),
                ),
                (
                    "producturl",
                    models.CharField(
                        max_length=200, verbose_name="Url producto detalle"
                    ),
                ),
                ("productdescription", models.TextField()),
                (
                    "productimg",
                    models.ImageField(
                        upload_to="static/img/",
                        verbose_name="Imagen principal del producto",
                    ),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.asesor",
                    ),
                ),
            ],
        ),
    ]
