# Generated by Django 4.1.5 on 2023-04-23 19:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "productmetadesc",
                    models.CharField(
                        max_length=200, verbose_name="Meta descripción del Producto"
                    ),
                ),
                (
                    "productkeywords",
                    models.CharField(
                        max_length=200, verbose_name="Palabras clave del Producto"
                    ),
                ),
                (
                    "productogdesc",
                    models.CharField(
                        max_length=200, verbose_name="Descripción OG del Producto"
                    ),
                ),
                (
                    "productogtitle",
                    models.CharField(
                        max_length=200, verbose_name="Titulo OG del Producto"
                    ),
                ),
                (
                    "productogurl",
                    models.CharField(
                        max_length=200, verbose_name="Url OG del Producto"
                    ),
                ),
                (
                    "productogimg",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Microformato del Producto"
                    ),
                ),
                (
                    "productogurlsec",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Segura del Producto"
                    ),
                ),
                (
                    "productname",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "productslogan",
                    models.CharField(
                        max_length=200, verbose_name="Slogan del Producto"
                    ),
                ),
                ("productoldprice", models.IntegerField(verbose_name="Precio normal")),
                (
                    "productdiscount",
                    models.IntegerField(verbose_name="Valor de descuento"),
                ),
                (
                    "producturl",
                    models.CharField(
                        max_length=200, verbose_name="Url producto detalle"
                    ),
                ),
                ("productdescription", ckeditor.fields.RichTextField()),
                (
                    "productimg",
                    models.ImageField(
                        upload_to="static/img/uploads/",
                        verbose_name="Imagen principal del Producto",
                    ),
                ),
                (
                    "productprice",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Precio de venta",
                    ),
                ),
                (
                    "asesor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.asesor",
                    ),
                ),
            ],
        ),
    ]
