# Generated by Django 4.1.5 on 2023-04-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_product_productimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productimg",
            field=models.ImageField(
                upload_to="static/img/uploads/",
                verbose_name="Imagen principal del Producto",
            ),
        ),
    ]
