# Generated by Django 4.1.5 on 2023-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_product_productimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productimg",
            field=models.ImageField(
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen principal del Producto",
            ),
        ),
    ]
