# Generated by Django 4.1.5 on 2023-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "productos",
            "0006_remove_product_additional_images_product_gallerya_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productbanner",
            field=models.ImageField(
                default="./static/img/default.jpg",
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen Banner del Producto",
            ),
        ),
    ]
