# Generated by Django 4.1.5 on 2023-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_product_productbanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productbanner",
            field=models.ImageField(
                default="/productos/static/img/default.jpg",
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen Banner del Producto",
            ),
        ),
    ]
