# Generated by Django 4.1.5 on 2023-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0008_alter_product_productbanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productbannermov",
            field=models.ImageField(
                default="/productos/static/img/default-mov.jpg",
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen Banner del Producto en Móvil",
            ),
        ),
    ]
