# Generated by Django 4.1.5 on 2023-05-05 15:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0009_product_productbannermov"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pagename",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la página"
                    ),
                ),
                (
                    "pagemetatitle",
                    models.CharField(
                        max_length=200, verbose_name="Metatítulo(title) de la página"
                    ),
                ),
                (
                    "pagetitle",
                    models.CharField(
                        max_length=200, verbose_name="Título(h1) de la página"
                    ),
                ),
                (
                    "pageslogan",
                    models.CharField(
                        max_length=200, verbose_name="Slogan(h2) de la página"
                    ),
                ),
                (
                    "pagemetadesc",
                    models.CharField(
                        max_length=200, verbose_name="Meta descripción de la página"
                    ),
                ),
                (
                    "pagekeywords",
                    ckeditor.fields.RichTextField(
                        verbose_name="Palabras clave de la página"
                    ),
                ),
                (
                    "pagebanner",
                    models.ImageField(
                        default="/productos/static/img/default.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen Banner de la página",
                    ),
                ),
                (
                    "pagebannermov",
                    models.ImageField(
                        default="/productos/static/img/default-mov.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen Banner de la página en Móvil",
                    ),
                ),
                (
                    "pageogdesc",
                    models.CharField(
                        max_length=200, verbose_name="Descripción OG de la página"
                    ),
                ),
                (
                    "pageogtitle",
                    ckeditor.fields.RichTextField(
                        verbose_name="Palabras clave de la página"
                    ),
                ),
                (
                    "pageogurl",
                    models.CharField(
                        max_length=200, verbose_name="Url OG de la página"
                    ),
                ),
                (
                    "pageogimg",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Microformato de la página"
                    ),
                ),
                (
                    "pageogurlsec",
                    models.CharField(
                        max_length=200, verbose_name="Url OG Segura de la página"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="galleryc",
            field=models.ImageField(
                blank=True,
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen final del Producto",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="galleryb",
            field=models.ImageField(
                blank=True,
                upload_to="imagenes-decortinas/",
                verbose_name="Imagen adicional del Producto",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="productkeywords",
            field=ckeditor.fields.RichTextField(
                verbose_name="Palabras clave del Producto"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="productogtitle",
            field=ckeditor.fields.RichTextField(
                verbose_name="Palabras clave del Producto"
            ),
        ),
    ]
