# Generated by Django 4.1.5 on 2023-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0014_alter_product_productdiscount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagina",
            name="pageogtitle",
            field=models.CharField(
                max_length=200, verbose_name="Título OG de la página"
            ),
        ),
    ]
