# Generated by Django 4.1.5 on 2023-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0016_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "videoname",
                    models.CharField(max_length=200, verbose_name="Nombre del video"),
                ),
                (
                    "videourl",
                    models.CharField(max_length=200, verbose_name="URL del video"),
                ),
            ],
        ),
    ]
