# Generated by Django 4.1.5 on 2023-05-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0017_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productupdated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
