# Generated by Django 4.1.5 on 2023-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0018_product_productupdated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promoname",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la promoción"
                    ),
                ),
                (
                    "widepromo",
                    models.ImageField(
                        default="/productos/static/img/default-mov.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen wide promo",
                    ),
                ),
                (
                    "movilpromo",
                    models.ImageField(
                        default="/productos/static/img/default-mov.jpg",
                        upload_to="imagenes-decortinas/",
                        verbose_name="Imagen movil promo",
                    ),
                ),
            ],
        ),
    ]
